"""empty message

Revision ID: 1762d783395f
Revises: 56549e03e3eb
Create Date: 2026-04-27 15:39:00.097403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1762d783395f'
down_revision: Union[str, Sequence[str], None] = '56549e03e3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Añadimos `status` con server_default='PENDING' para que las fundaciones
    # ya existentes en la BD reciban un valor válido al hacer la migración.
    # El default Python en el modelo (FoundationStatus.PENDING) sigue siendo
    # quien decide en filas nuevas creadas desde la app.
    op.add_column(
        'foundations',
        sa.Column(
            'status',
            sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='foundation_status'),
            nullable=False,
            server_default='PENDING',
        ),
    )
    op.create_index(op.f('ix_foundations_status'), 'foundations', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foundations_status'), table_name='foundations')
    op.drop_column('foundations', 'status')
    # ### end Alembic commands ###
