"""empty message

Revision ID: 68d7bc9c7887
Revises: 88e0e8ba9ce8
Create Date: 2026-04-27 14:26:37.465893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d7bc9c7887'
down_revision: Union[str, Sequence[str], None] = '88e0e8ba9ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('image_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'image_public_id')
    # ### end Alembic commands ###
