"""empty message

Revision ID: 88e0e8ba9ce8
Revises: 
Create Date: 2026-04-27 11:36:51.904172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e0e8ba9ce8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adopters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('google_id', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adopters_email'), 'adopters', ['email'], unique=True)
    op.create_index(op.f('ix_adopters_google_id'), 'adopters', ['google_id'], unique=True)
    op.create_table('foundations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('adoptions', sa.Integer(), nullable=False),
    sa.Column('initial', sa.String(length=2), nullable=False),
    sa.Column('gradient_from', sa.String(length=9), nullable=False),
    sa.Column('gradient_to', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foundations_city'), 'foundations', ['city'], unique=False)
    op.create_index(op.f('ix_foundations_email'), 'foundations', ['email'], unique=True)
    op.create_index(op.f('ix_foundations_google_id'), 'foundations', ['google_id'], unique=True)
    op.create_index(op.f('ix_foundations_name'), 'foundations', ['name'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('PERRO', 'GATO', name='pet_type'), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('vaccinated', sa.Boolean(), nullable=False),
    sa.Column('sterilized', sa.Boolean(), nullable=False),
    sa.Column('is_adopted', sa.Boolean(), nullable=False),
    sa.Column('gradient_from', sa.String(length=9), nullable=False),
    sa.Column('gradient_to', sa.String(length=9), nullable=False),
    sa.Column('foundation_id', sa.Integer(), nullable=False),
    sa.Column('adopter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adopter_id'], ['adopters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['foundation_id'], ['foundations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_adopter_id'), 'pets', ['adopter_id'], unique=False)
    op.create_index(op.f('ix_pets_city'), 'pets', ['city'], unique=False)
    op.create_index(op.f('ix_pets_foundation_id'), 'pets', ['foundation_id'], unique=False)
    op.create_index(op.f('ix_pets_is_adopted'), 'pets', ['is_adopted'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index(op.f('ix_pets_is_adopted'), table_name='pets')
    op.drop_index(op.f('ix_pets_foundation_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_city'), table_name='pets')
    op.drop_index(op.f('ix_pets_adopter_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_foundations_name'), table_name='foundations')
    op.drop_index(op.f('ix_foundations_google_id'), table_name='foundations')
    op.drop_index(op.f('ix_foundations_email'), table_name='foundations')
    op.drop_index(op.f('ix_foundations_city'), table_name='foundations')
    op.drop_table('foundations')
    op.drop_index(op.f('ix_adopters_google_id'), table_name='adopters')
    op.drop_index(op.f('ix_adopters_email'), table_name='adopters')
    op.drop_table('adopters')
    # ### end Alembic commands ###
